#### I. Importing needed libraries

In [1]:
import pandas as pd
import numpy as np

#### II. Getting the dataset, and assigning X, y

In [5]:
dataset = pd.read_csv("auto-mpg.data.csv", )
dataset

    18.0   8   307.0      130.0      3504.      12.0   70  1\t"chevrolet chevelle malibu"
0    15.0   8   350.0      165.0      3693.      11...
1    18.0   8   318.0      150.0      3436.      11...
2    16.0   8   304.0      150.0      3433.      12...
3    17.0   8   302.0      140.0      3449.      10...
4    15.0   8   429.0      198.0      4341.      10...
5    14.0   8   454.0      220.0      4354.       9...
6    14.0   8   440.0      215.0      4312.       8...
7    14.0   8   455.0      225.0      4425.      10...
8    15.0   8   390.0      190.0      3850.       8...
9    15.0   8   383.0      170.0      3563.      10...
10   14.0   8   340.0      160.0      3609.       8...
11   15.0   8   400.0      150.0      3761.       9...
12   14.0   8   455.0      225.0      3086.      10...
13   24.0   4   113.0      95.00      2372.      15...
14   22.0   6   198.0      95.00      2833.      15...
15   18.0   6   199.0      97.00      2774.      15...
16   21.0   6   200.0      85.00      2587.      16...
17   27.0   4   97.00      88.00      2130.      14...
18   26.0   4   97.00      46.00      1835.      20...
19   25.0   4   110.0      87.00      2672.      17...
20   24.0   4   107.0      90.00      2430.      14...
21   25.0   4   104.0      95.00      2375.      17...
22   26.0   4   121.0      113.0      2234.      12...
23   21.0   6   199.0      90.00      2648.      15...
24   10.0   8   360.0      215.0      4615.      14...
25   10.0   8   307.0      200.0      4376.      15...
26   11.0   8   318.0      210.0      4382.      13...
27   9.0    8   304.0      193.0      4732.      18...
28   27.0   4   97.00      88.00      2130.      14...
29   28.0   4   140.0      90.00      2264.      15...
..                                                 ...
367  27.0   4   112.0      88.00      2640.      18...
368  34.0   4   112.0      88.00      2395.      18...
369  31.0   4   112.0      85.00      2575.      16...
370  29.0   4   135.0      84.00      2525.      16...
371  27.0   4   151.0      90.00      2735.      18...
372  24.0   4   140.0      92.00      2865.      16...
373  23.0   4   151.0      ?          3035.      20...
374  36.0   4   105.0      74.00      1980.      15...
375  37.0   4   91.00      68.00      2025.      18...
376  31.0   4   91.00      68.00      1970.      17...
377  38.0   4   105.0      63.00      2125.      14...
378  36.0   4   98.00      70.00      2125.      17...
379  36.0   4   120.0      88.00      2160.      14...
380  36.0   4   107.0      75.00      2205.      14...
381  34.0   4   108.0      70.00      2245       16...
382  38.0   4   91.00      67.00      1965.      15...
383  32.0   4   91.00      67.00      1965.      15...
384  38.0   4   91.00      67.00      1995.      16...
385  25.0   6   181.0      110.0      2945.      16...
386  38.0   6   262.0      85.00      3015.      17...
387  26.0   4   156.0      92.00      2585.      14...
388  22.0   6   232.0      112.0      2835       14...
389  32.0   4   144.0      96.00      2665.      13...
390  36.0   4   135.0      84.00      2370.      13...
391  27.0   4   151.0      90.00      2950.      17...
392  27.0   4   140.0      86.00      2790.      15...
393  44.0   4   97.00      52.00      2130.      24...
394  32.0   4   135.0      84.00      2295.      11...
395  28.0   4   120.0      79.00      2625.      18...
396  31.0   4   119.0      82.00      2720.      19...

[397 rows x 1 columns]

In [ ]:
m